login/urls.py
from django.conf.urls import url
from . import views



urlpatterns = [

    url(r'^$', views.register, name = 'reg'),
]

music/urls.py
from django.conf.urls import url
from . import views #importing views from same directory(.)


app_name = 'music' #this is called Namespace used to distinguish names of urls(if they are same)
                   #eg: if we have 2 apps music and videos and both have details html page then on which regex which template will be executed so it is distinguished by Namespace.

urlpatterns = [
    # regex starts at ^ and ends at $
    #this maps url /music/
    #as_view() functions converts classes to views
    url(r'^$', views.IndexView.as_view(), name='index'), #this regex r'^$' means that user has just requested music/ and nothing else.

    #this maps url /music/21/
    #<pk> is the primary key in which the class of details view expects, brackets are so that 21 is read as 21 an not 2 and 1
    # [0-9] means any digit b/w 0 to 9 and + means it will read id character by character

    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='details'),

    #/music/album/add
    url(r'^album/add/$',views.AlbumCreate.as_view(), name='album-add'),

    #/music/album/pk/
    url(r'^album/(?P<pk>[0-9]+)/$',views.AlbumUpdate.as_view(),name='album-update'),

    #music/album/pk/delete
    #url(r'^album/(?P<pk>[0-9]+)/delete/$',views.DeleteView.as_view(),name='album-delete')

    url(r'^register/$', views.UserFormView.as_view(), name='register')



]

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url(r'^$', include('login.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

login/models.py
from django.db import models

# Create your models here.

music/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.

class Album(models.Model): #always all the classes are inherited with models.Model
    artist = models.CharField(max_length= 250) #CharField is just text or characters and max_length is max charaters it can have
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()


    def get_absolute_url(self):
        return reverse('music:details', kwargs={'pk': self.pk}) #go to details view with pk of current object,

    '''this is a string dunder(double underscores) function which will show the info about objects of 
        album class in django shell while populating database. '''
    '''basically __str__ func. displays the string info of a class.'''
    def __str__(self):
        return self.artist + ' - ' + self.album_title


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE) #every song is from an album so we are linking songs to album via foreign key coz album will have a primary key which will be auto generated.
    # on_delete=models.CASCADE is telling that when the album gets deleted, delete all its song from this table.

    song_title = models.CharField(max_length=500)
    file_type = models.CharField(max_length=100)
    is_favorite = models.BooleanField(default = False)

    def __str__(self):
        return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput) #to give password the asterik look (*)

    class Meta:
        model = User
        fields = ['username','email','password'] #fields which we will be using for form and this will be added to database

login/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.


def register(request):
    return HttpResponse('<h1>Hello</h1>')

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .models import Album
from .forms import UserForm


class IndexView(generic.ListView): #inheriting the generic list view, there are other generic views here we are using list
    template_name = 'music/index.html' #template name to which this class plugins
    context_object_name = 'all_albums' #context object name is the fixed variable name,it is used to change name of object_list to any name you want like here all albums

    def get_queryset(self): #queries database for all objects in album and returns object_list
        return Album.objects.all()


class DetailView(generic.DetailView): #using the generic detail view
    model = Album #which model we are refering
    template_name = 'music/details.html'


class AlbumCreate(CreateView): #now you want to create a view
    model = Album #what type of object will new view have? ans-Album, oh so we we are making a new album
    fields = ['artist', 'album_title', 'genre', 'album_logo'] #what fields will the new album have/we want to show.


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']



#class AlbumDelete(DeleteView):
 #   model = Album
  #  success_url = reverse_lazy('music:index') #when we will delete  any view so it will take us to index.html
    #success_url is used when we successfully delete something.

class UserFormView(View):
    form_class = UserForm #blueprint from where we will take our form
    template_name = 'music/registration_form.html' #html file associated with form_class

    #display a blank form to user
    def get(self,request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form':form})



    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid(): #this will check the basic validation, is_valid does the basic validation of our form
            user = form.save(commit=False) #form is saved to an object user but not to database

            #cleaned normalized data so that every one has uniform pattern

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user.set_password(password) #hash value password is stored in DB and not plain text,if plain text is stored ot will throw errors

            user.save() #saved to database

            user = authenticate(username = username, password =password) #authenticate the user if he./she is in DB(already registered)

            if user is not None: #if user is there
                if user.is_active: #and if user is active i.e his account is not disabled or banned by website company.
                    login(request,user) #user is permitted to login(session is given to him/her)
                    return redirect('music:index') #after login he/she is redirected to home page

        return render(request,self.template_name,{'form':form}) #if user is not in DB he is given blank form

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block albums_active %}active{% endblock %} #dont know what this does

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data"> <!--action is empty coz it will land on same page -->
                        {% csrf_token %}
                       {% include 'music/form-template.html' %} <!--include code from form-template.html-->
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>

                            </div>
                        </div>
                </div>

            </div>

        </div>

    </div>
</div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Cool Website{% endblock %}</title> <!-- title is just the name of the block-->
    <!-- this cdn bootstrap link, in this we do not have to download bootstrap it is stored on someone else's computer in the world and we just refer to it-->
    <!-- cdn = Content Delivery Network -->
    <link rel = "stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel="stylesheet" type="text/css">
    <link rel = "stylesheet" type="text/css" href="{% static 'music/details_style.css' %} "/>
</head>
<body>
<nav class = "navbar navbar-inverse">
    <div class = "container-fluid">
        <!-- Logo Viberr if we click on it we will get to home page(index.html) of website -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <!-- 3 spans to put 3 lines(the icon that appears on top right corner to display contents in menu) when the screen is squeezedor if it is open on mobile phones-->
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
        </div>

        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; <!-- puts CD icon in from of Album-->
                        Albums
                    </a>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;<!-- puts music icon in front of Songs-->
                        Songs
                    </a>

            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'music:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Add Albums
                    </a>
                <li class="">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Logout
                    </a>

            </ul>

        </div>

    </div>

</nav>
{% block body %} <!-- body is just the name of the block-->
{% endblock %}
</body>
</html>

music/templates/music/details.html
{% extends 'music/base.html' %}
{% block title %}Album Details{% endblock %}

{% block body %}
    {% load staticfiles %}
    <link rel="stylesheet" type = "text/css" href="{% static 'music/details_style.css' %}" />


    <h1>{{album.album_title}}</h1>
    <h3>{{album.artist}}</h3>
    {% if error_message %}
        <p><strong>{{error_message}}</strong></p>
    {% endif %}
    <form>
        {% csrf_token %}
        {% for song in album.song_set.all %}
            <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}"/>
            <label for="song{{ forloop.counter }}">
                {{ song.song_title }}

             </label><br>
        {% endfor %}

    </form>
{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10"> <!--basic validation handelled by bootstrap -->
        <span class="text-danger small">{{field.errors}}</span>
    </div>
    <label class="control-label col-sm-2">{{ field.label_tag}}</label> <!--this displays the elements of fields list- album name. artist ,logo etc-->
    <div class="col-sm-10">{{field}}</div> <!-- this displays the field box in which we will write-->


</div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %} <!-- to include a template -->

{% block body %}
    {% load staticfiles %}

<div class="container-fluid">
    <div class="panel panel-default">
        <div class="panel-body">


            <!--{% for album in all_albums %}-->
    <div class="row">
            <div class="col-sm-3">
            <div class="card">
                <img class="card-img-top" src="{{album.album_logo.url}}" alt="Card image">
                <div class="card-block">
                    <h4 class="card-title">{{album.album_title}}</h4>
                    <p class="card-text">{{album.artist}}</p>
                    <p class="card-text"><small class="text-muted">{{album.genre}}</small></p>


                    <a href="{% url 'music:details' album.id %}" class="btn btn-primary">Details</a>
                </div>
            </div>
           <!-- {% endfor %}-->
        </div>
<!--
        <div class="col-sm-3">
            <div class="card">
                <img class="card-img-top" src="{% static 'music/guitar.jpeg' %}" alt="Card image">
                <div class="card-block">
                    <h4 class="card-title">Card title</h4>
                    <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
                    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                    <a href="{% url 'music:details' 2 %}" class="btn btn-primary">Details</a>
                </div>
            </div>
        </div>
-->
    </div>
    </div>
    </div>
</div>



{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}Registration{% endblock %}


{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create New User</h3>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data"> <!--action is empty coz it will land on same page -->
                        {% csrf_token %}
                       {% include 'music/form-template.html' %} <!--include code from form-template.html-->
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>

                            </div>
                        </div>
                </div>

            </div>

        </div>

    </div>
</div>
{% endblock %}